/*  GENERATES /vv-margin.js , THE PER-CARD rt STANDARD-ERROR TABLE THE MARGIN GATE READS.
    Input: /tmp/se_all.json from `SAMPLE=all REPS=200 MODEL=pois node bootstrap_se.js`.

    WHY PER CARD AND NOT A MODEL. Three compact fallbacks were measured against the
    per-card truth over 400,000 pairs and all three were rejected:
        rt only                     11.16% of pairs decided differently   (87 entries)
        rt x minutes bucket         10.60%                                (608 entries)
        rt x minutes x pool          4.12%                              (4,115 entries)
    A gate that decides whether to crown cannot be wrong on one pairing in twenty-four.
    SE varies up to 5.8x WITHIN a single rt value below 80, which is why no coarse key works.

    THE PACKING. One printable character per card_id slot, indexed by card_id - BASE.
    Character 32 (space) means "no card here"; 33..126 encode SE = (code-33) * 0.2.
    Quantising to 0.2 rt costs 0.225% of pair decisions, measured, and nothing clamps
    (max SE 17.82 against a ceiling of 18.6).  */
const fs=require('fs');
const se=JSON.parse(fs.readFileSync('/tmp/se_all.json','utf8'));
const STEP=0.2;
const ids=se.map(r=>r.card_id);
const BASE=Math.min(...ids), TOP=Math.max(...ids);
const span=TOP-BASE+1;
const arr=new Array(span).fill(32);
let clamped=0;
for(const r of se){
  let q=Math.round(r.se/STEP);
  if(q>93){ q=93; clamped++; }
  if(q<0) q=0;
  arr[r.card_id-BASE]=33+q;
}
const str=arr.map(c=>String.fromCharCode(c)).join('');
const out=`/*  vv-margin.js , PER-CARD rt STANDARD ERROR, FOR THE COMPARE MARGIN GATE.
    GENERATED by scripts/separability/gen_margin_table.js , DO NOT HAND-EDIT.

    WHAT IT IS. For every scored outfield card, the standard error of its VV Score, from a
    parametric bootstrap of the engine (200 replicates, Poisson counting noise, every other
    card held fixed). Method, validation and controls: scripts/separability/README.md.

    WHY IT EXISTS. Compare crowned a winner on any rt gap at all. Measured, that crowns a
    winner the engine cannot support on 61.9% of the comparisons people have actually made,
    and 97.0% of all pairings at rt 80+ sit inside the Index's own margin of error. The gate
    keyed on THIS table replaces a constant gap, because the error is not constant , it runs
    from 0.96 rt at Generational to 5.79 at Standout and varies 1.5x within a single rt value.

    POISSON IS THE FRIENDLIEST ASSUMPTION AVAILABLE TO THE CROWN, and that is deliberate.
    It is the MINIMUM plausible variance for count data; under overdispersed counts every SE
    rises and more pairings fall inside the margin. Shipping the narrow model means the gate
    crowns MORE often than a stricter reading would, so no crown is withheld on a technicality.

    THIS IS AN EMBEDDED SNAPSHOT AND NOTHING WARNS YOU WHEN IT GOES STALE. It is the THIRD
    of its kind , KEEPER_SAVE_LADDER and RADAR_POOL_REF are the others , and section C
    already records that two was a class rather than a coincidence. REGENERATE IT after any
    population-moving write: a re-ingest, the transfer-halves repair, a position backfill, or
    any engine change. The card ids it does not know fail CLOSED (no crown), so a stale table
    under-crowns rather than crowning wrongly, which is the safe direction but is still wrong.
    The permanent fix is an rt_se column at the shared matview rebuild.  */
(function(){
  'use strict';
  var BASE=${BASE}, STEP=${STEP}, N=${se.length};
  var SE=${JSON.stringify(str)};
  /*  null means "this card is not in the snapshot", NEVER "its error is zero". The caller
      must fail closed on null , an unknown error cannot justify a crown.  */
  function seFor(cardId){
    if(cardId==null) return null;
    var i=cardId-BASE;
    if(i<0||i>=SE.length) return null;
    var c=SE.charCodeAt(i);
    if(c===32) return null;
    return (c-33)*STEP;
  }
  var Z=1.96;
  /*  THE MARGIN IS THE PAIR'S OWN, NOT A CONSTANT. Two independent estimates, so the
      pooled error is the root sum of squares, and 1.96 of it is the conventional 95%
      two-sided bar , the same bar the separability audit reports against.  */
  function marginFor(a,b){
    var sa=seFor(a), sb=seFor(b);
    if(sa==null||sb==null) return null;
    return Z*Math.sqrt(sa*sa+sb*sb);
  }
  var API={ seFor:seFor, marginFor:marginFor, Z:Z, STEP:STEP, BASE:BASE, COUNT:N };
  if(typeof window!=='undefined') window.VVMargin=API;
  if(typeof module!=='undefined'&&module.exports) module.exports=API;
})();
`;
/*  ABSOLUTE, NEVER RELATIVE. A bare 'vv-margin.js' resolves against the CWD, so running this
    from scripts/separability/ wrote the table into the SCRIPT directory while still printing
    "wrote vv-margin.js" , a success message about a file nobody reads. Caught on 2026-09-12 by
    the repo-root file's timestamp not moving, which is not a check anyone should have to invent.  */
const OUT = require('path').join(__dirname, '..', '..', 'vv-margin.js');
fs.writeFileSync(OUT, out);
console.log('wrote '+OUT);
console.log('  cards       :', se.length);
console.log('  card_id span:', BASE, 'to', TOP, '=', span, 'slots');
console.log('  clamped     :', clamped);
console.log('  file bytes  :', fs.statSync('vv-margin.js').size.toLocaleString());
