-- Stage-0 engine baseline snapshot , load engine_baseline_snapshot.csv into Supabase for rt-diffing
-- across the recalibration stages (Decisions 1-3, see VVonderXI_Engine_Design_Log.md).
-- Generated by scripts/engine/baseline_snapshot.js (read-only from player_card_mv). Run in your lane.

-- 1) Table (run in the Supabase SQL editor):
CREATE TABLE IF NOT EXISTS engine_baseline_snapshot (
  card_id       integer PRIMARY KEY,
  player_name   text,
  season_year   integer,
  position_pool text,
  position      text,
  rt            integer
);

-- 2) Load the CSV data. RECOMMENDED , Node loader (in Claude's lane, robust for 56k, correct NULL typing):
--      NODE_PATH=./node_modules node scripts/engine/load_baseline_to_supabase.js --write
--    (Just run the CREATE TABLE above in the SQL editor first; the loader batch-upserts via the service key.)
--    Fallbacks: (a) Supabase dashboard Table Editor -> engine_baseline_snapshot -> "Import data from CSV"
--    (browser upload, slower for 56k, watch empty rt cells -> NULL). (b) psql \copy , needs the direct
--    Postgres connection string + psql CLI (NOT the PostgREST service key in .env). The web SQL editor
--    does NOT support \copy.

-- 3) Diff any later stage (baseline vs current matview):
--   SELECT b.card_id, b.player_name, b.season_year, b.position_pool,
--          b.rt AS baseline_rt, mv.rt AS new_rt, (mv.rt - b.rt) AS delta
--   FROM engine_baseline_snapshot b
--   JOIN player_card_mv mv USING (card_id)
--   ORDER BY delta DESC;

-- 4) Per-pool mean shift (are CB/FB rising as intended, ST peaks holding?):
--   SELECT mv.position_pool,
--          round(avg(b.rt), 1)  AS baseline_mean,
--          round(avg(mv.rt), 1) AS new_mean,
--          round(avg(mv.rt - b.rt), 1) AS mean_delta
--   FROM engine_baseline_snapshot b
--   JOIN player_card_mv mv USING (card_id)
--   GROUP BY mv.position_pool
--   ORDER BY mean_delta DESC;
