CREATE INDEX idx_mv_api_player ON public.player_card_mv USING btree (api_player_id);
CREATE UNIQUE INDEX idx_mv_card_id ON public.player_card_mv USING btree (card_id);
CREATE INDEX idx_mv_era ON public.player_card_mv USING btree (season_year);
CREATE INDEX idx_mv_league ON public.player_card_mv USING btree (league_code);
CREATE INDEX idx_mv_name_norm ON public.player_card_mv USING btree (player_name_norm text_pattern_ops);
CREATE INDEX idx_mv_name_trgm ON public.player_card_mv USING gin (player_name_norm gin_trgm_ops);
CREATE INDEX idx_mv_pname_trgm ON public.player_card_mv USING gin (player_name gin_trgm_ops);
CREATE INDEX idx_mv_pos ON public.player_card_mv USING btree (position_pool);
CREATE INDEX idx_mv_rt ON public.player_card_mv USING btree (rt);
CREATE INDEX idx_mv_team_norm ON public.player_card_mv USING btree (team_name_norm text_pattern_ops);
CREATE INDEX idx_mv_team_trgm ON public.player_card_mv USING gin (team_name_norm gin_trgm_ops);