-- STEP 2 , build the replacement BESIDE the live one. NO OUTAGE, nothing reads _new yet.
-- 65 columns: the 47 the live matview already has, + 8 defensive (Group D, already on the
-- view), + 6 keeper/penalty (Group A), + 4 discipline (Group B).
-- penalties_won is deliberately EXCLUDED , see 08_drop_penalties_won.sql.
-- Group C (percentiles) is deliberately EXCLUDED , POST_LAUNCH names none of the eight
-- stats and gates them on three decisions that need the distributions visible first.
-- Expect this to take roughly 10-20s: the source view's full scan measured 4,486 ms.
CREATE MATERIALIZED VIEW public.player_card_mv_new AS
 SELECT
    card_id,
    player_id,
    api_player_id,
    player_name,
    nationality,
    date_of_birth,
    is_retired,
    is_legacy,
    legacy_tier,
    season,
    season_year,
    league_code,
    league_name,
    league_flag,
    league_strength_weight,
    team_name,
    primary_colour,
    secondary_colour,
    accent_colour,
    "position",
    age,
    appearances,
    minutes,
    goals,
    assists,
    output,
    adj_output,
    rating,
    rt,
    shots_total,
    shots_on,
    passes_total,
    passes_key,
    passes_accuracy,
    dribbles_attempts,
    dribbles_success,
    tackles_total,
    tackles_blocks,
    interceptions,
    duels_total,
    duels_won,
    estimated_market_value,
    season_age,
    position_pool,
    shirt_number,
    player_name_norm,
    team_name_norm,
    def90,
    defvol_pct,
    team_def90,
    def_share,
    def_share_pct,
    def90_pool_pct,
    duel_rate,
    duel_quality_pct,
    starts,
    goals_conceded,
    saves,
    penalties_scored,
    penalties_missed,
    penalties_saved,
    fouls_drawn,
    fouls_committed,
    cards_yellow,
    cards_red
   FROM player_card_view;
