/*  BAM README GENERATOR , writes exports/bam/README.md and NOTHING ELSE.
    ================================================================
    WHY THIS EXISTS. The README said "Generated ... regenerate with
    check-coverage.js" and nothing generated it: check-coverage.js only prints,
    and the file was typed. It went stale inside two days , it said "no match
    data" while nine platform-league exports sat beside it, and it still listed
    thirteen columns after Round and RegularSeason were appended. A file that
    claims to be generated and is not is worse than one that admits it is typed,
    because nobody re-checks it.

    WHERE EACH PART COMES FROM, so none of it is retyped:
      status                  check-coverage.js, run as a child process and its
                              output embedded verbatim , the two cannot disagree
      the fourteen leagues    reference/shots_coverage_by_league.json (bam_leagues)
      absent-shots leagues    the same file, shots_absent_entirely
      Eredivisie percentages  the same file, eredivisie_measured_per_season
      platform exports        each <slug>/manifest.json that is NOT a brief slug
      column list             the header line in export-league-csv.js
      alias count             reference/club_alias_map.json, alias_entries
    Everything else is TEMPLATE PROSE below. Edit it here, never in the output.

    READ-ONLY. No API calls, no database, no writes but the one file.
*/
'use strict';
const fs=require('fs'), path=require('path'), cp=require('child_process');
const ROOT=path.resolve(__dirname,'..','..'), BAM=path.join(ROOT,'exports','bam');
const OUT=path.join(BAM,'README.md');
const refDoc=JSON.parse(fs.readFileSync(path.join(BAM,'reference','shots_coverage_by_league.json'),'utf8'));
const ref=refDoc.bam_leagues;
const aliases=JSON.parse(fs.readFileSync(path.join(BAM,'reference','club_alias_map.json'),'utf8'));
const {idNames}=require('./club-identity.js');

// ---- status: check-coverage.js verbatim. It exits 1 on any gap, which is data, not failure.
const cov=cp.spawnSync(process.execPath,[path.join(__dirname,'check-coverage.js')],{encoding:'utf8'});
if(cov.error||cov.stdout==null||!/leagues exported\./.test(cov.stdout)){
  console.error('REFUSING TO WRITE , check-coverage.js did not produce a report.');
  console.error(cov.error||cov.stderr); process.exit(1);
}
const covText=cov.stdout.trimEnd();
const briefSlugs=Object.keys(ref);
const exportedBrief=briefSlugs.filter(s=>fs.existsSync(path.join(BAM,s)));

// ---- column list from the exporter itself, never retyped
const exporterSrc=fs.readFileSync(path.join(__dirname,'export-league-csv.js'),'utf8');
const colMatch=exporterSrc.match(/const lines=\['(Date,[^']+)'\]/);
if(!colMatch){ console.error('REFUSING TO WRITE , column header not found in export-league-csv.js'); process.exit(1); }
const columns=colMatch[1];

// ---- platform exports: every directory with a manifest that is not a brief slug
const platform=fs.readdirSync(BAM)
  .filter(d=>!briefSlugs.includes(d) && fs.existsSync(path.join(BAM,d,'manifest.json')))
  .sort()
  .map(d=>({dir:d, m:JSON.parse(fs.readFileSync(path.join(BAM,d,'manifest.json'),'utf8'))}));

const yy=(y)=>`${y}/${String(y+1).slice(2)}`;
const byId=Object.entries(ref).sort((a,b)=>a[1].league_id-b[1].league_id);
const absent=byId.filter(([,s])=>s.shots_absent_entirely);
const n=(x)=>x.toLocaleString('en-GB');

const L=[];
const P=(...a)=>L.push(...a);
const today=new Date().toISOString().slice(0,10);

P('# BAM export , coverage and status','',
`Generated ${today} by \`node scripts/bam/gen-readme.js\`. **Do not edit this file by hand** ,`,
'every figure is read from the exports, the reference files or the exporter, and the prose is a',
'template inside the script. Edit the script and re-run it.','');

// ---- STATUS
P('## STATUS , THE FOURTEEN-LEAGUE BRIEF','');
if(exportedBrief.length===0){
  P(`**Not delivered. ${exportedBrief.length} of ${briefSlugs.length} brief leagues are exported.** The platform-league`,
    'match exports further down are a different set of leagues and do not count toward the brief.','');
}else if(exportedBrief.length<briefSlugs.length){
  P(`**Partly delivered. ${exportedBrief.length} of ${briefSlugs.length} brief leagues are exported.**`,'');
}else{
  P(`**All ${briefSlugs.length} brief leagues are exported.** Gaps, if any, are listed per league below.`,'');
}
P('Output of `node scripts/bam/check-coverage.js` at generation time, verbatim:','','```',covText,'```','');

// ---- FOURTEEN LEAGUES
P(`## THE ${briefSlugs.length===14?'FOURTEEN':briefSlugs.length} LEAGUES`,'',
'| slug | API id | first season the API holds | our floor | seasons expected | shots from |',
'|---|---|---|---|---|---|');
for(const [slug,s] of byId){
  P(`| \`${slug}\` | ${s.league_id} | ${yy(s.api_first_season)} | ${yy(s.requested_floor)} | ${s.expected_season_count} | ${s.shots_absent_entirely?'**no shots, ever**':s.shots_label} |`);
}
P('');

// ---- PLATFORM EXPORTS
if(platform.length){
  const tot=platform.reduce((a,{m})=>{
    a.matches+=m.seasons.reduce((x,s)=>x+s.match_count,0);
    a.calls+=(m.total_calls||0); return a;},{matches:0,calls:0});
  P('## THE PLATFORM-LEAGUE MATCH EXPORTS , NOT THE BRIEF','',
  `**${platform.length} further exports sit in this directory and they are VVonderXI's own leagues, not the`,
  `${briefSlugs.length} above.** They share the file format and the checks below; \`check-coverage.js\` does not read them,`,
  'because it measures the brief. Read from each `manifest.json`:','',
  '| dir | API id | seasons | first | last | matches | missing | seasons with shots | retrieved | calls |',
  '|---|---|---|---|---|---|---|---|---|---|');
  for(const {dir,m} of platform){
    const ss=m.seasons.map(s=>s.season);
    P(`| \`${dir}\` | ${m.league_id} | ${m.seasons.length} | ${yy(Math.min(...ss))} | ${yy(Math.max(...ss))} | ${n(m.seasons.reduce((x,s)=>x+s.match_count,0))} | ${m.seasons.reduce((x,s)=>x+s.missing_count,0)} | ${m.seasons.filter(s=>s.shots).length} | ${String(m.retrieved_at).slice(0,10)} | ${m.total_calls!=null?n(m.total_calls):'NR'} |`);
  }
  P('',`Total: **${n(tot.matches)} matches**, **${n(tot.calls)} calls** as recorded in the manifests.`,'');
  // club identity across seasons, from each names_<dir>.csv , the finding BAM most needs if it keys on names
  const idf=[];
  for(const {dir} of platform){ const r=idNames(path.join(BAM,'names_'+dir+'.csv'));
    if(r.state==='NO_MAP') idf.push(`- \`${dir}\`: **no names map, identity across seasons unchecked**`);
    r.findings.forEach(f=>idf.push(`- \`${dir}\` ${f.kind}${f.id?' (ApiTeamId '+f.id+')':''}: ${f.detail}`)); }
  P('**Club identity across seasons**, read from each `names_<dir>.csv` by `ApiTeamId`:','',
    ...(idf.length?idf:['- none: every id carries one name and every name one id']),'',
    'A RENAME is not a defect in the export, but a consumer that keys clubs by NAME will split that',
    'club\'s history at the rename. Join on `ApiTeamId`.','');
  const overlap=platform.filter(({m})=>byId.some(([,s])=>s.league_id===m.league_id));
  for(const {dir,m} of overlap){
    const [bslug]=byId.find(([,s])=>s.league_id===m.league_id);
    P(`**OVERLAP, UNRESOLVED: \`${dir}\` carries API league ${m.league_id}, the same id as the brief's \`${bslug}\`.**`,
      `\`check-coverage.js\` looks under \`${bslug}/\` and does not read \`${dir}/\`. Whether that export satisfies the`,
      'brief\'s row is not established here , it is a decision, not something this file can derive.','');
  }
}

// ---- TEMPLATE PROSE, with the derived values injected
const ere=refDoc.eredivisie_measured_per_season||{};
const erePart=Object.entries(ere).filter(([,v])=>v.pct>0 && v.pct<100);
const ereShots=erePart.map(([,v])=>Math.round(v.pct)+'%');
const ereSpan=erePart.length?`${erePart[0][0].slice(0,4)}-${erePart[erePart.length-1][0].slice(0,4)}`:'NR';
const ereFull=Object.entries(ere).find(([,v])=>v.pct>=100);
const ereFirst=Object.entries(ere).find(([,v])=>v.pct>0);

P('## '+(absent.length===2?'TWO':absent.length)+' THINGS GENUINELY ABSENT, NOT MERELY OLD','',
`**${absent.map(([s,v])=>`\`${s}\` (${v.league_id})`).join(' and ')} have NO fixture`,
'statistics in ANY season.** `HS`, `AS`, `HST` and `AST` will be empty on every row, in',
'every year, permanently. That is the API, not a gap in the pull, and no re-run changes it.',
(absent.length===1?'It still carries':'Both leagues still carry')+' full results , dates, clubs, full-time and half-time scores.','',
'**`HxG` and `AxG` are empty on every row of every league.** API-Football does not serve',
'expected goals on this plan , probed on Eredivisie, the Premier League and La Liga: sixteen',
'statistic types, none of them xG. The columns are kept so BAM\'s reader does not change, and',
'they are **not** derived from shots. A proxy BAM computes is BAM\'s model; a number we',
'invented under an xG heading would be ours wearing BAM\'s name.','');

P('## THE SHOTS BOUNDARY IS FIRST-APPEARANCE, NOT COMPLETENESS','',
'The column above says when shots first appear. **It does not mean every season after it is',
`fully covered.** Measured on Eredivisie: the flag says ${ereFirst?ereFirst[0]:'NR'}, and actual per-match`,
`coverage ran **${ereShots.join(', ')}** across ${ereSpan}, reaching 100% only from **${ereFull?ereFull[0]:'NR'}**.`,'',
'**Read the measured figure, not the flag.** Every `meta_<SEASON>.json` carries',
'`shots_coverage.rows_with_shots` against `rows_total`. Fitting a shots-based model on a',
'season that is half covered will quietly weight it wrong.','');

P('## A SEASON WITH NO FIXTURES IS THREE DIFFERENT THINGS, AND ONLY ONE IS A DEFECT','',
'If a season\'s file carries no fixtures, `check-coverage.js` classifies it rather than',
'reporting a blank, because the three causes need different responses and only one is ours:','',
'| classification | meaning | is it a defect? |','|---|---|---|',
'| `NOT_PUBLISHED` | the season exists, its fixture list is not out yet | no , expected before kickoff |',
'| `NOT_STARTED` | the API holds the season and returns nothing for it | no , a fact about the source |',
'| `DROPPED` | the API returned rows and our export wrote none | **yes , ours to fix** |','',
'Each `meta_<SEASON>.json` records **`api_results`**, the count the provider returned, beside',
'the number of rows written. That is what makes the third case provable instead of inferred:',
'without it, an empty season is ambiguous between "the API had none" and "we lost them", and',
'a league BAM cannot price would look identical to a league that has not started.','',
'The classification for the brief leagues is in the check output under STATUS above.','');

P('## FILE FORMAT','',
'Per league, per season: `<slug>_<SEASON>.csv` and `meta_<SEASON>.json`, plus',
'`names_<slug>.csv` and `manifest.json`.','',
'Columns, in order, read from the exporter:','','```',columns,'```','',
'- `Date` is `DD/MM/YYYY` from the UTC kickoff.',
'- **Every listed fixture is a row, played or not.** An unplayed fixture carries its date and',
'  both clubs and leaves every score and shot column **empty** , never `0`. A zero is a',
'  result; an empty cell is not.',
'- `HTHG`/`HTAG` come from the same response as the full-time score. No extra call.',
'- `Round` is the API\'s own round label. `RegularSeason` is 1 when that label begins',
'  `Regular Season`, else 0 , play-offs are labelled and kept, not filtered, so every',
'  inclusion policy is one predicate on the reader\'s side.',
'- Counts, the through-date and the missing-fixture flag live in `meta_<SEASON>.json`, never',
'  as rows inside the CSV.','');

P('## THE CLUB-NAME CHECK','',
'A fixture list naming clubs differently from the results splits a club\'s rating with nothing',
'failing. Every season\'s meta carries `club_names`: the played and unplayed name counts and',
'any name appearing in only one set. **Two checks read it, because one comparison cannot cover',
'both states of a season** (`scripts/bam/club-identity.js`):','',
'- **In-season.** A fixture naming a club the results never do is a split, and so, while the',
'  season is still running, is a results-only name. **On a COMPLETED season there are no unplayed',
'  fixtures, so the comparison is NOT APPLICABLE** , reported as such, never counted as a pass.',
'- **Across seasons.** `names_<slug>.csv` carries `ApiTeamId`. One id under two names with',
'  overlapping seasons is a SPLIT, one name under two ids a COLLISION; disjoint seasons are a',
'  RENAME, listed for any consumer that keys on names.','',
'**The `match` boolean in each meta is NOT meaningful on a completed season**: it compares',
'played against an empty unplayed set and reads false on 93 of 94 platform seasons, none of them',
'a real split. Read `only_in_unplayed`, or the check output above, not `match`.','',
'The in-season comparison was verified on Eredivisie 2026/27 before the format was settled , 18',
'clubs on both sides, zero asymmetry, because both sets come from the same response.','',
'`reference/canonical_clubs.json` holds our club vocabulary to map against, and',
`\`reference/club_alias_map.json\` the ${aliases.alias_entries} aliases we derived, with the traps named , \`Verona\``,
'fuzzy-matches `Everton` above the correct `Hellas Verona`.','');

// the CANC example is read from whichever export holds Eredivisie 2019/20; dropped if none does
let canc=null;
for(const d of fs.readdirSync(BAM)){
  const f=path.join(BAM,d,'meta_2019.json');
  if(!fs.existsSync(f)) continue;
  const m=JSON.parse(fs.readFileSync(f,'utf8'));
  if(m.league_id===88 && m.unplayed_with_reason && m.unplayed_with_reason.CANC){ canc=m.unplayed_with_reason.CANC; break; }
}
P('## MISSING VERSUS NOT YET PLAYED','',
'`missing_count` in each meta means: listed, kicked off, no result returned, and no stated',
'reason. A future date is not-yet-played and is never flagged. A postponement or cancellation',
'is reported under its own name'+(canc?` , Eredivisie 2019/20 carries ${canc} \`CANC\` fixtures, the season`:'.'),
...(canc?['abandoned to COVID.']:[]),'',
'**The limit:** it compares results against the returned fixture list, which is the only',
'fixture source. A match never listed cannot be detected. The round census in each meta is',
'the independent check, and it is regular-season only.');

fs.writeFileSync(OUT,L.join('\n')+'\n');
console.log(`wrote ${path.relative(ROOT,OUT)} , ${exportedBrief.length}/${briefSlugs.length} brief leagues, ${platform.length} platform exports`);
